### ISSUE TITLE
Buttons & Drop-down menus on the GUI

### ISSUE THREAD

**Issue by ACovaci99** [ACovaci99/I_Love_Science_Fest#1]
For the GUI, I would like to have the following drop-down menus implemented
- scale (this will contain a couple of cities)
- meteorological scenario (this will contain a handful of situations such as summer day, summer night, storm, winter night ...) 

The exact values of the drop-down menus (and possibly even some additional buttons/menus) are still to be determined, depending on how much I can extend my model. The variables of these drop-down menus will be used as input for the back end. What method would you suggest we use to transmit these values to the back end?
@hosseindehghanipour1998

**Comment by hosseindehghanipour1998** [comment]
I wrote the code for this part and so far it works with JSON. If I receive a JSON file in the following format (see below) from you, I can directly use it.


# JSON Format:
File Name: **city_scales.JSON**
File Format:
```
city_scales  {

    "Antwerpen": "1.5",
    "Brussels": "1",
    "Leuven": "2.5"
}
```

1. If you put the name of the cities completely as it is how it is supposed to be shown, would be perfect.
2. The value (scale) should also be in string format otherwise reading the JSON will face an error (API stuff). I will have to convert them to __float__ directly in the code while reading the file.
